"""
共享 fixtures 与配置

策略：
- 后端服务必须已在 BASE_URL（默认 http://127.0.0.1:8000）运行
- 测试用项目以 fixture 形式按 session 生命周期创建，结束时删除
- 不实际跑仿真轮（需要 LLM 调用），仅验证控制端点的响应
"""

from __future__ import annotations

import os
import time
from typing import Iterator

import httpx
import pytest


BASE_URL = os.environ.get("ABM_TEST_BASE_URL", "http://127.0.0.1:8000")
API_PREFIX = "/api/v1"


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line(
        "markers",
        "slow: marks tests as slow (e.g. running real simulation rounds with LLM)",
    )


@pytest.fixture(scope="session")
def base_url() -> str:
    return BASE_URL


@pytest.fixture(scope="session")
def api_url() -> str:
    return BASE_URL + API_PREFIX


@pytest.fixture(scope="session")
def client(base_url: str) -> Iterator[httpx.Client]:
    """复用同一个 httpx Client，节省连接开销。"""
    with httpx.Client(base_url=base_url, timeout=30.0) as c:
        # 后端必须已经启动
        try:
            r = c.get("/health")
            r.raise_for_status()
        except Exception as e:  # pragma: no cover
            pytest.exit(
                f"后端未在 {base_url} 启动或不可达：{e}\n"
                f"请先运行：python start.py 或 uvicorn app.main:app --reload",
                returncode=2,
            )
        yield c


@pytest.fixture(scope="session")
def smoke_project(client: httpx.Client) -> Iterator[dict]:
    """
    创建一个 smoke 测试专用项目，session 结束时清理。
    所有依赖项目的测试通过该 fixture 拿到 project_id。
    """
    payload = {
        "project_name": f"smoke_test_{int(time.time())}",
        "project_desc": "auto-generated by test suite",
        "total_rounds": 3,
        "scene_source": "自定义",
    }
    resp = client.post(f"{API_PREFIX}/simulation/project", json=payload)
    assert resp.status_code == 200, resp.text
    project = resp.json()
    project_id = project["project_id"]

    yield project

    # 清理
    try:
        client.delete(f"{API_PREFIX}/simulation/project/{project_id}")
    except Exception:
        pass


@pytest.fixture(scope="session")
def smoke_project_with_agents(
    client: httpx.Client, smoke_project: dict
) -> dict:
    """
    在 smoke_project 之上添加 3 个 agent（覆盖超级大国/大国/小国），
    并初始化战略关系。返回 dict 含 project_id 与 agent_ids。
    """
    project_id = smoke_project["project_id"]

    # 真实 CINC 数据（USA-2016, CHN-2016, RUS-2016 量级），保证 power_level 自动判定
    agent_payloads = [
        {
            "agent_name": "测试超级大国A",
            "region": "美洲",
            "milex": 600000.0, "milper": 1400.0, "irst": 78.0,
            "pec": 2200000.0, "tpop": 320000.0, "upop": 260000.0,
            "country_code": 2, "cinc_year": 2016, "leader_type": "霸权型",
        },
        {
            "agent_name": "测试大国B",
            "region": "亚洲",
            "milex": 200000.0, "milper": 2300.0, "irst": 800.0,
            "pec": 3000000.0, "tpop": 1380000.0, "upop": 760000.0,
            "country_code": 710, "cinc_year": 2016, "leader_type": "王道型",
        },
        {
            "agent_name": "测试小国C",
            "region": "欧洲",
            "milex": 50000.0, "milper": 800.0, "irst": 70.0,
            "pec": 700000.0, "tpop": 144000.0, "upop": 105000.0,
            "country_code": 365, "cinc_year": 2016, "leader_type": None,
        },
    ]

    agent_ids = []
    for payload in agent_payloads:
        resp = client.post(
            f"{API_PREFIX}/simulation/project/{project_id}/agent", json=payload
        )
        assert resp.status_code == 200, f"add agent failed: {resp.text}"
        agent_ids.append(resp.json()["agent_id"])

    # 初始化战略关系
    resp = client.post(
        f"{API_PREFIX}/strategic-relationships/project/{project_id}/initialize"
    )
    assert resp.status_code == 200, resp.text

    return {"project_id": project_id, "agent_ids": agent_ids}
