"""
端到端集成测试 - 完整仿真生命周期

与 test_backend_smoke.py::TestSimulationControl 不同，本套件实际运行一段
短真实-LLM 仿真（2 轮 / 3 agents），并验证整个数据管道：
仿真完成 → 单轮详情 → 统计端点 → 后验分析端点 → LLM 调用日志。

所有用例标记 @pytest.mark.slow，仅在显式 --slow / 选中运行。
环境变量 ABM_E2E_SKIP=1 可整体跳过本模块。

依赖 conftest.py 的 client fixture（共享 httpx Client + 健康检查）。
"""

from __future__ import annotations

import os
import time
from typing import Iterator

import httpx
import pytest


API = "/api/v1"

# 单轮轮询间隔 / 总超时(秒)
POLL_INTERVAL = 5.0
POLL_TIMEOUT = 300.0


# ========================================================================
# 模块级跳过守卫
# ========================================================================
pytestmark = pytest.mark.skipif(
    os.environ.get("ABM_E2E_SKIP") == "1",
    reason="ABM_E2E_SKIP=1 环境变量被设置，跳过端到端测试套件",
)


# ========================================================================
# 专用短项目 fixture (session 生命周期)
# ========================================================================
@pytest.fixture(scope="module")
def e2e_project(client: httpx.Client) -> Iterator[dict]:
    """
    创建一个 2 轮 / 3 agent 的端到端测试项目。

    步骤：
    1. POST /simulation/project (total_rounds=2, scene_source=自定义)
    2. POST /simulation/project/{pid}/agent x 3 (USA/CHN/FRA 量级)
    3. POST /strategic-relationships/project/{pid}/initialize
    4. POST /agent-neighbors/project/{pid}/initialize
       (若 404，pytest.skip 整个模块)
    5. yield {project_id, agent_ids}
    6. teardown: DELETE /simulation/project/{pid}
    """
    # 1) 创建项目
    project_payload = {
        "project_name": f"e2e_test_{int(time.time())}",
        "project_desc": "auto-generated by e2e integration test",
        "total_rounds": 2,
        "scene_source": "自定义",
    }
    resp = client.post(f"{API}/simulation/project", json=project_payload)
    assert resp.status_code == 200, f"创建项目失败: {resp.text}"
    project = resp.json()
    project_id = project["project_id"]

    # 2) 添加 3 个 agent (USA/CHN/FRA-like)
    agent_payloads = [
        {
            "agent_name": "E2E超级大国A",
            "region": "美洲",
            "milex": 600000.0, "milper": 1400.0, "irst": 78.0,
            "pec": 2200000.0, "tpop": 320000.0, "upop": 260000.0,
            "country_code": 2, "cinc_year": 2016, "leader_type": "霸权型",
        },
        {
            "agent_name": "E2E大国B",
            "region": "亚洲",
            "milex": 200000.0, "milper": 2300.0, "irst": 800.0,
            "pec": 3000000.0, "tpop": 1380000.0, "upop": 760000.0,
            "country_code": 710, "cinc_year": 2016, "leader_type": "王道型",
        },
        {
            "agent_name": "E2E中等国C",
            "region": "欧洲",
            "milex": 50000.0, "milper": 800.0, "irst": 70.0,
            "pec": 700000.0, "tpop": 144000.0, "upop": 105000.0,
            "country_code": 220, "cinc_year": 2016, "leader_type": None,
        },
    ]

    agent_ids: list[int] = []
    for payload in agent_payloads:
        r = client.post(
            f"{API}/simulation/project/{project_id}/agent", json=payload
        )
        if r.status_code != 200:
            # 清理后跳过(CINC 数据缺失等)
            client.delete(f"{API}/simulation/project/{project_id}")
            pytest.skip(
                f"创建 agent 失败 (可能 data/cinc.csv 缺少 USA/CHN/FRA 2016 行): "
                f"{r.status_code} {r.text}"
            )
        agent_ids.append(r.json()["agent_id"])

    # 3) 初始化战略关系
    r = client.post(
        f"{API}/strategic-relationships/project/{project_id}/initialize"
    )
    assert r.status_code == 200, f"初始化战略关系失败: {r.text}"

    # 4) 初始化邻接关系（端点存在性校验）
    r = client.post(
        f"{API}/agent-neighbors/project/{project_id}/initialize"
    )
    if r.status_code == 404:
        client.delete(f"{API}/simulation/project/{project_id}")
        pytest.skip(
            "POST /api/v1/agent-neighbors/project/{pid}/initialize 端点不存在 (404)"
        )
    assert r.status_code == 200, f"初始化邻接关系失败: {r.text}"

    yield {"project_id": project_id, "agent_ids": agent_ids}

    # teardown
    try:
        client.delete(f"{API}/simulation/project/{project_id}")
    except Exception:
        pass


# ========================================================================
# 端到端测试主体
# ========================================================================
@pytest.mark.slow
class TestE2EFullCycle:
    """完整生命周期：start → 轮询完成 → 单轮详情 → 统计 → 分析 → LLM日志。"""

    def test_start_run_to_completion(
        self, client: httpx.Client, e2e_project: dict
    ) -> None:
        """启动仿真并轮询直至完成 (上限 5 分钟)。"""
        pid = e2e_project["project_id"]

        # 重置到初始状态，规避 fixture 复用导致的脏状态
        client.post(f"{API}/simulation/{pid}/reset")

        r = client.post(f"{API}/simulation/{pid}/start")
        assert r.status_code == 200, f"启动失败: {r.text}"
        assert r.json().get("status") in ("运行中", "已完成"), \
            f"启动后状态异常: {r.json()}"

        # 轮询
        deadline = time.time() + POLL_TIMEOUT
        snapshot: dict = {}
        while time.time() < deadline:
            sr = client.get(f"{API}/simulation/project/{pid}")
            assert sr.status_code == 200, f"查询项目失败: {sr.text}"
            snapshot = sr.json()
            status = snapshot.get("status")
            current_round = snapshot.get("current_round", 0) or 0
            total_rounds = snapshot.get("total_rounds", 0) or 0
            if status == "已完成" or (total_rounds and current_round >= total_rounds):
                break
            time.sleep(POLL_INTERVAL)
        else:
            pytest.fail(
                f"仿真在 {POLL_TIMEOUT:.0f}s 内未完成，最后快照: {snapshot}"
            )

        assert snapshot.get("current_round", 0) >= 1, \
            f"完成后 current_round 应至少为 1, 实际: {snapshot}"

    def test_round_detail_populated_after_run(
        self, client: httpx.Client, e2e_project: dict
    ) -> None:
        """单轮详情：actions 列表非空（依赖前一测试）。"""
        pid = e2e_project["project_id"]
        r = client.get(f"{API}/simulation/{pid}/round/1")
        assert r.status_code == 200, f"查询单轮失败: {r.text}"
        body = r.json()
        assert isinstance(body, dict), f"返回应为 dict, 实际: {type(body)}"
        assert "actions" in body, f"返回缺少 actions 字段: {body.keys()}"
        actions = body["actions"]
        assert isinstance(actions, list), f"actions 应为 list, 实际: {type(actions)}"
        assert len(actions) > 0, f"第 1 轮 actions 列表不应为空: {body}"

    def test_stats_endpoints_populated(
        self, client: httpx.Client, e2e_project: dict
    ) -> None:
        """关键统计端点应在仿真完成后返回非空数据。"""
        pid = e2e_project["project_id"]

        # 非空 list
        for stat in ("power-history", "power-growth-rate",
                     "action-preference", "order-evolution"):
            r = client.get(f"{API}/simulation/{pid}/stats/{stat}")
            assert r.status_code == 200, f"{stat} 请求失败: {r.text}"
            data = r.json()
            assert isinstance(data, list), f"{stat} 应返回 list"
            assert len(data) > 0, f"{stat} 仿真完成后不应为空"

        # 可能为空但需 200
        r = client.get(f"{API}/simulation/{pid}/stats/goal-evaluations")
        assert r.status_code == 200, f"goal-evaluations 请求失败: {r.text}"
        assert isinstance(r.json(), list), "goal-evaluations 应返回 list"

        # 关系图：节点 >= 3
        r = client.get(f"{API}/simulation/{pid}/stats/agent-relations")
        assert r.status_code == 200, f"agent-relations 请求失败: {r.text}"
        relations = r.json()
        assert isinstance(relations, dict), "agent-relations 应返回 dict"
        assert "nodes" in relations, f"缺少 nodes 字段: {relations.keys()}"
        assert len(relations["nodes"]) >= 3, \
            f"节点数应至少 3, 实际: {len(relations['nodes'])}"

    def test_analysis_endpoints_populated(
        self, client: httpx.Client, e2e_project: dict
    ) -> None:
        """后验分析端点应返回非空 dict。"""
        pid = e2e_project["project_id"]
        for endpoint in ("behavior", "power", "order", "leader", "report"):
            r = client.get(f"{API}/analysis/{pid}/{endpoint}")
            assert r.status_code == 200, f"analysis/{endpoint} 失败: {r.text}"
            data = r.json()
            assert isinstance(data, dict), \
                f"analysis/{endpoint} 应返回 dict, 实际: {type(data)}"
            assert len(data) > 0, f"analysis/{endpoint} 不应返回空 dict"

    def test_llm_call_log_captured(
        self, client: httpx.Client, e2e_project: dict
    ) -> None:
        """LLM 调用日志：仿真运行至少产生一次调用，详情含完整 prompt。"""
        pid = e2e_project["project_id"]
        r = client.get(f"{API}/llm-calls/project/{pid}")
        assert r.status_code == 200, f"llm-calls 列表请求失败: {r.text}"
        body = r.json()
        assert isinstance(body, dict), f"应返回 dict, 实际: {type(body)}"
        assert "total" in body, f"缺少 total 字段: {body.keys()}"
        assert body["total"] > 0, \
            f"仿真完成后 LLM 调用数应 > 0, 实际: {body['total']}"

        items = body.get("items", [])
        assert len(items) > 0, "items 列表不应为空"
        call_id = items[0]["call_id"]

        r2 = client.get(f"{API}/llm-calls/{call_id}")
        assert r2.status_code == 200, f"llm-calls/{call_id} 请求失败: {r2.text}"
        detail = r2.json()
        assert "prompt_full" in detail, \
            f"详情缺少 prompt_full 字段: {detail.keys()}"
        assert detail["prompt_full"], \
            f"prompt_full 不应为空, 实际: {detail.get('prompt_full')!r}"

    def test_pause_resume_after_completion_is_idempotent(
        self, client: httpx.Client, e2e_project: dict
    ) -> None:
        """已完成项目调用 pause/resume 应优雅返回 200，不应崩溃。"""
        pid = e2e_project["project_id"]
        r = client.post(f"{API}/simulation/{pid}/pause")
        assert r.status_code == 200, \
            f"已完成项目 pause 应优雅返回 200, 实际: {r.status_code} {r.text}"

        r = client.post(f"{API}/simulation/{pid}/resume")
        assert r.status_code == 200, \
            f"已完成项目 resume 应优雅返回 200, 实际: {r.status_code} {r.text}"
